# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: fast-stein-correction

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest isort black
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint check
      run: |
        flake8 --ignore=E501,W503 stein --exclude stein/__init__.py,stein/benchmark/__init__.py,stein/model/__init__.py
        black --check stein/
        isort --check stein/

    - name: Test with pytest
      run: |
        pytest stein/test
